apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: sample
  name: myapp-rails-ing
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: myapp-rails 
          servicePort: 80

